In [21]:
import pandas as pd
import sqlite3

## Load the OnlineRetail Dataset

import pandas as pd
import sqlite3

## Load the OnlineRetail Dataset

In [22]:
df_retail = pd.read_csv('/content/OnlineRetail.csv', encoding='ISO-8859-1')
display(df_retail.head())

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

## Data Overview and Initial Cleaning

In [23]:
print(df_retail.info())
print(df_retail.shape)
print(df_retail.columns)

# Clean column names (remove leading/trailing spaces)
df_retail.columns = df_retail.columns.str.strip()

# Convert object columns to lowercase (if applicable, though 'InvoiceNo' and 'StockCode' might be mixed case)
for col in df_retail.select_dtypes(include='object').columns:
    df_retail[col] = df_retail[col].astype(str).str.lower()

display(df_retail.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB
None
(541909, 8)
Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123a,white hanging heart t-light holder,6,12/1/2010 8:26,2.55,17850.0,united kingdom
1,536365,71053,white metal lantern,6,12/1/2010 8:26,3.39,17850.0,united kingdom
2,536365,84406b,cream cupid hearts coat hanger,8,12/1/2010 8:26,2.75,17850.0,united kingdom
3,536365,84029g,knitted union flag hot water bottle,6,12/1/2010 8:26,3.39,17850.0,united kingdom
4,536365,84029e,red woolly hottie white heart.,6,12/1/2010 8:26,3.39,17850.0,united kingdom

## Handle Missing Values

In [24]:
print(df_retail.isnull().sum())

# Drop rows with any missing values
df_retail = df_retail.dropna()

print(f"Shape after dropping nulls: {df_retail.shape}")

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64
Shape after dropping nulls: (406829, 8)

## Handle Duplicate Rows

In [25]:
print(f"Number of duplicated rows: {df_retail.duplicated().sum()}")

# Drop duplicate rows
df_retail = df_retail.drop_duplicates()

print(f"Shape after dropping duplicates: {df_retail.shape}")

Number of duplicated rows: 5225
Shape after dropping duplicates: (401604, 8)

## Descriptive Statistics

In [26]:
print("\nDescriptive statistics for numerical columns:")
display(df_retail.describe())

print("\nDescriptive statistics for object columns:")
display(df_retail.describe(include='object'))

Descriptive statistics for numerical columns:

            Quantity      UnitPrice     CustomerID
count  401604.000000  401604.000000  401604.000000
mean       12.183273       3.474064   15281.160818
std       250.283037      69.764035    1714.006089
min    -80995.000000       0.000000   12346.000000
25%         2.000000       1.250000   13939.000000
50%         5.000000       1.950000   15145.000000
75%        12.000000       3.750000   16784.000000
max     80995.000000   38970.000000   18287.000000

Descriptive statistics for object columns:

,InvoiceNo,StockCode,Description,InvoiceDate,Country
count,401604,401604,401604,401604,401604
unique,22190,3684,3896,20460,37
top,576339,85123a,white hanging heart t-light holder,11/14/2011 15:27,united kingdom
freq,542,2065,2058,543,356728

## Save Cleaned Data

In [28]:
# Save to CSV
df_retail.to_csv("cleaned_online_retail.csv", index=False)

# Save to JSON
df_retail.to_json("cleaned_online_retail.json", orient="records", indent=4)
print("Cleaned data saved to 'cleaned_online_retail.csv' and 'cleaned_online_retail.json'.")

Cleaned data saved to 'cleaned_online_retail.csv' and 'cleaned_online_retail.json'.

## Load Data into SQLite Database and Perform Queries

In [29]:
# Establish SQLite connection and load data
connection_retail = sqlite3.connect("online_retail.db")
df_retail.to_sql("retail_transactions", connection_retail, if_exists="replace", index=False)
print(f"Successfully loaded {df_retail.shape[0]} records into 'retail_transactions' table.")

Successfully loaded 401604 records into 'retail_transactions' table.

In [30]:
print("\nFirst 5 rows from the database:")
display(pd.read_sql("SELECT * FROM retail_transactions LIMIT 5;", connection_retail))

First 5 rows from the database:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123a,white hanging heart t-light holder,6,12/1/2010 8:26,2.55,17850.0,united kingdom
1,536365,71053,white metal lantern,6,12/1/2010 8:26,3.39,17850.0,united kingdom
2,536365,84406b,cream cupid hearts coat hanger,8,12/1/2010 8:26,2.75,17850.0,united kingdom
3,536365,84029g,knitted union flag hot water bottle,6,12/1/2010 8:26,3.39,17850.0,united kingdom
4,536365,84029e,red woolly hottie white heart.,6,12/1/2010 8:26,3.39,17850.0,united kingdom

In [31]:
print("\nTransactions with Quantity greater than 10:")
display(pd.read_sql("SELECT * FROM retail_transactions WHERE Quantity > 10 LIMIT 5;", connection_retail))

Transactions with Quantity greater than 10:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536367,84879,assorted colour bird ornament,32,12/1/2010 8:34,1.69,13047.0,united kingdom
1,536370,22728,alarm clock bakelike pink,24,12/1/2010 8:45,3.75,12583.0,france
2,536370,22727,alarm clock bakelike red,24,12/1/2010 8:45,3.75,12583.0,france
3,536370,22726,alarm clock bakelike green,12,12/1/2010 8:45,3.75,12583.0,france
4,536370,21724,panda and bunnies sticker sheet,12,12/1/2010 8:45,0.85,12583.0,france

In [32]:
print("\nTransactions ordered by UnitPrice (descending), top 5:")
display(pd.read_sql("SELECT * FROM retail_transactions ORDER BY UnitPrice DESC LIMIT 5;", connection_retail))

Transactions ordered by UnitPrice (descending), top 5:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,c556445,m,manual,-1,6/10/2011 15:31,38970.00,15098.0,united kingdom
1,c551685,post,postage,-1,5/3/2011 12:51,8142.75,16029.0,united kingdom
2,551697,post,postage,1,5/3/2011 13:46,8142.75,16029.0,united kingdom
3,c551699,m,manual,-1,5/3/2011 14:12,6930.00,16029.0,united kingdom
4,c560372,m,manual,-1,7/18/2011 12:26,4287.63,17448.0,united kingdom

In [33]:
print("\nTotal transactions per Country:")
display(pd.read_sql("SELECT Country, COUNT(*) AS total_transactions FROM retail_transactions GROUP BY Country ORDER BY total_transactions DESC LIMIT 5;", connection_retail))

Total transactions per Country:

          Country  total_transactions
0  united kingdom              356728
1         germany                9480
2          france                8475
3            eire                7475
4           spain                2528

In [42]:
# The error "ProgrammingError: Cannot operate on a closed database." indicates that
# the database connection 'connection_retail' was closed by a previous cell
# (likely the cell containing `connection_retail.close()`) before this cell tried to use it.
# To ensure this query runs, we will re-establish the connection.

connection_retail = sqlite3.connect("online_retail.db")

print("\nTotal number of records in the database:")
display(pd.read_sql("SELECT COUNT(*) AS total_records FROM retail_transactions;", connection_retail))

Total number of records in the database:

   total_records
0         401604

In [43]:
print("\nAverage Quantity of items:")
display(pd.read_sql("SELECT AVG(Quantity) AS average_quantity FROM retail_transactions;", connection_retail))

Average Quantity of items:

   average_quantity
0         12.183273

In [44]:
print("\nMaximum UnitPrice:")
display(pd.read_sql("SELECT MAX(UnitPrice) AS max_unit_price FROM retail_transactions;", connection_retail))

Maximum UnitPrice:

   max_unit_price
0         38970.0

In [45]:
print("\nMinimum UnitPrice:")
display(pd.read_sql("SELECT MIN(UnitPrice) AS min_unit_price FROM retail_transactions;", connection_retail))

Minimum UnitPrice:

   min_unit_price
0             0.0

In [46]:
print("\nTotal sum of Quantity:")
display(pd.read_sql("SELECT SUM(Quantity) AS total_quantity FROM retail_transactions;", connection_retail))

Total sum of Quantity:

   total_quantity
0         4892851

In [48]:
print("\nCountries with more than 1000 transactions:")
display(pd.read_sql("SELECT Country, COUNT(*) AS total FROM retail_transactions GROUP BY Country HAVING COUNT(*) > 1000 ORDER BY total DESC;", connection_retail))

Countries with more than 1000 transactions:

           Country   total
0   united kingdom  356728
1          germany    9480
2           france    8475
3             eire    7475
4            spain    2528
5      netherlands    2371
6          belgium    2069
7      switzerland    1877
8         portugal    1471
9        australia    1258
10          norway    1086

In [47]:
print("\nFirst 10 records from the database:")
display(pd.read_sql("SELECT * FROM retail_transactions LIMIT 10;", connection_retail))

First 10 records from the database:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123a,white hanging heart t-light holder,6,12/1/2010 8:26,2.55,17850.0,united kingdom
1,536365,71053,white metal lantern,6,12/1/2010 8:26,3.39,17850.0,united kingdom
2,536365,84406b,cream cupid hearts coat hanger,8,12/1/2010 8:26,2.75,17850.0,united kingdom
3,536365,84029g,knitted union flag hot water bottle,6,12/1/2010 8:26,3.39,17850.0,united kingdom
4,536365,84029e,red woolly hottie white heart.,6,12/1/2010 8:26,3.39,17850.0,united kingdom
5,536365,22752,set 7 babushka nesting boxes,2,12/1/2010 8:26,7.65,17850.0,united kingdom
6,536365,21730,glass star frosted t-light holder,6,12/1/2010 8:26,4.25,17850.0,united kingdom
7,536366,22633,hand warmer union jack,6,12/1/2010 8:28,1.85,17850.0,united kingdom
8,536366,22632,hand warmer red polka dot,6,12/1/2010 8:28,1.85,17850.0,united kingdom
9,536367,84879,assorted colour bird ornament,32,12/1/2010 8:34,1.69,13047.0,united kingdom

In [35]:
# Close the database connection
connection_retail.close()
print("SQLite connection closed.")

SQLite connection closed.